### ISSUE TITLE
MVP Módulo Redes

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-microservices#126]
Tornar possível a utilização do match para mais de uma comunidade

**Comment by talitanovacoski** [comment]
### Cronograma da Missão

**Março**
**1ª quinzena (10 e 11/03)**
**1) Imersão de dois dias em SP ou RJ (Nossas e All Out)**
Criar a identidade da rede de solidariedade: nome, design, narrativa, voz da marca e página.
Criar comunicações para chamada de voluntários de mapeamento
Treinar equipe All Out no processo de match e gestão do atendimento
Aproveitando o encontro presencial de todos, faremos o módulo de capacitação:
Oficina com voluntárias estratégicas sobre a capacitação para psicólogas

**2ª quinzena**
2) Chamada de voluntários de mapeamento, acolhimento e comunicação (All Out)
3) Desenvolvimento dos conteúdos e metodologias das oficinas (Nossas)

**Abril**
**1ª quinzena**
1) Seleção dos voluntários (All Out e Nossas)
2) Realização do treinamento online introdutório para voluntários (Nossas)

**2ª quinzena**
3) Realização do treinamento online de mapeamento (Nossas) 
4) Realização do treinamento presencial de acolhimento (Nossas)
5) Realização do treinamento online de comunicação (Nossas) 

**Maio**
**1ª quinzena**
1) Lançamento suave do Mapa (inicialmente focado em inscrições de voluntárias psicólogas) (All Out e Nossas)

**2ª quinzena**
2) Lançamento público do Mapa (inicialmente focado em inscrições de voluntárias psicólogas) (All Out e Nossas)
3) Mutirão de triagem das voluntárias psicólogas (All Out e Nossas)
4) Lançamento do cadastro de pessoas em situação de risco (All Out e Nossas)

**Junho**
1) Mutirão de match e início dos acolhimentos (All Out)

**Julho**
1) Acompanhamento (All Out)

**Agosto**
1) Acompanhamento (All Out)
2) Decisão sobre expansão (All Out)

**Comment by talitanovacoski** [comment]
### Sobre a triagem

**Status do indivíduo**
Inscrita (Indisponível, com o campo disponibilidade desabilitado);
Reprovada (Indisponível, com o campo disponibilidade desabilitado);
Aprovada (Disponível, com o campo disponibilidade habilitado);

**Disponibilidade**
Disponível;
Indisponível;
Anti-ética (conduta inapropriada); 
Férias; 
Licença;
Descadastrada (pediu para se descadastrar);

**Comment by talitanovacoski** [comment]
### Sobre Relações

**Status:**
Encaminhamento: Realizado
(O encaminhamento foi feito, mas o início do atendimento ainda não foi confirmado)

Atendimento: Iniciado
(Recebemos confirmação de que o atendimento está em andamento)

Atendimento: Concluído 
(Recebemos confirmação de que o atendimento foi concluído)

Atendimento: Interrompido
(Houve algum impedimento ao longo do atendimento, caso analisado pela agente)
