### ISSUE TITLE
Definir estratégia para desativar o uso do bonde-zendesk em python

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-microservices#127]
Considerar o processo de geolocalização do pedido que hoje está dentro da integração propriamente dita.

**Comment by lpirola** [comment]
- [ ] criar issue com estratégia definida

**Comment by lpirola** [comment]
@igr-santos @vivianedias a estratégia mais simples, é criar outro webhook no hasura que funcionará ao lado do bonde-zendesk em python hoje e que removerá a lógica de converter o cep/endereço em latitude e logitude dele.

O ideal é alterar a widget de form e adicionar um campo do tipo endereço mas seria muito complexo para resolver nessa semana.

Concordam?

**Comment by vivianedias** [comment]
entao esse webhook tomaria conta de fazer essa conversão? @lpirola

**Comment by lpirola** [comment]
sim

**Comment by lpirola** [comment]
Será necessário uma migração de arquitetura. 

Cada resposta no form_entries estará relacionado a um solidarity_users e um solidarity_tickets.

O users como lista de pessoas e o tickets como atualizações sobre o relacionamento com o users.

A integração com zendesk passa a funcionar em 2 momentos: na criação do registro no form_entries no BONDE e na atualização dos tickets no ZENDESK. Na primeira enviando dados e na segunda recebendo atualizações sobre o relacionamento.

Outra integração, é a com o cálculo da geolocalização, feito por relacionamento iniciado, ou para cada assinatura do formulário.

Existe uma qualificação automatizada com base nas respostas do formulário do mautic e que deve continuar dessa forma pois não será utilizada pelo mapa lgbt.

As ferramentas cli-mautic e cli-zendesk continuarão a servir como forma de sincronizar dados dessas integrações.

Os novos packages existentes na nova arquitetura são:

* volunteer process qualified zendesk (webhooks-zendesk) - triggcer no webhook do mautic
* match-zendesk (webhooks-solidarity-match) - trigger no webhook do hasura
* volunteer availability zendesk (webhooks-solidarity-count) - trigger no webhook do ticket do zendesk
* (webhooks-registry) - trigger no 
* cli mautic
* cli zendesk
* solidarity client
* geolocation manager
* person manager
* group manager
*

**Comment by lpirola** [comment]
A estratégia é simplificar, faremos apenas a conexão de um formulário com as tabelas do módulo de redes e a qualificação da informação de endereço.

https://app.zenhub.com/workspaces/nossas-5dcc03646fa9b600011bd62a/issues/nossas/bonde-migrations/41

https://app.zenhub.com/workspaces/nossas-5dcc03646fa9b600011bd62a/issues/nossas/bonde-microservices/140

Com isso já é possível acessar os dados de forma contextualizada utilizando apenas graphql.
