### ISSUE TITLE
Criar interface reutilizável de seleção de comunidade e usuário

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-microservices#130]
Criar interface reutilizável de seleção de comunidade e usuário

- [ ] aplicar no cliente do módulo solidariedade e 
- [ ] aplicar no cliente do admin canary

**Comment by lpirola** [comment]
@igr-santos provavelmente a versão em typescript do styleguide não será compatível com versões anteriores.

Um ponto essencial q me parece importante na mudança para melhorar a tipagem é o uso de funções ao invés de classes.

**Comment by igr-santos** [comment]
@lpirola vou voltar essa issue pra `in-progress` ou `backlog` pois ela não está em review, ou está? ela já foi finalizada, se executar build, testes e integração vai funcionar?

**Comment by lpirola** [comment]
voltei para o backlog
