### ISSUE TITLE
Criar listener para sincronizar dados do form_entry para o rede_individuals e rede_groups de acordo com o rede_settings

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-microservices#153]

**Comment by lpirola** [comment]
@igr-santos https://github.com/nossas/bonde-microservices/commit/70e8d801b983934b65d9709e840d1bf7d8284a2f

**Comment by igr-santos** [comment]
- [ ] Remover tabela settings, usar como referencia grupos
- [ ] Individuals sempre são inseridos como triagem, cabe ao usuário verficar dados replicados no caso de preenchimento da mesma pessoa
- [ ] Parse dos form_entries em dados normalizados Individuals
