### ISSUE TITLE
Adc possibilidade de filtrar a tabela Pessoas por grupos, status e disponibilidade

### ISSUE THREAD

**Issue by vivianedias** [nossas/bonde-microservices#171]
- [x] Grupos é um multi-select
- [x] Status é um select
- [x] Disponibilidade é um select

**Comment by igr-santos** [comment]
Filtro funcionando com base em dados filtrados diretamente na API, no futuro quando começarmos a replicar essa lógica de tabela é preciso uma refatoração pra tornar o código mais simples de manutenção
