### ISSUE TITLE
Adicionar tela de configuração da comunidade

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-microservices#187]
Nessa tela de configurações da rede da comunidade, essas variáveis devem ser configuradas a partir do input do usuário:
- distancia 
- msg de whatsapp p/ voluntária
- msg de whatsapp p/ psr

**Comment by lpirola** [comment]
No primeiro momento, fazer apenas a alteração estática do valor do raio de busca.

**Comment by vivianedias** [comment]
A alteração estática da distância foi feita nesse PR #195

**Comment by vivianedias** [comment]
Distancia foi alterada novamente para 4000km no PR #202

**Comment by vivianedias** [comment]
Nessa tela de configurações da rede da comunidade, essas variáveis devem ser configuradas a partir do input do usuário:
- distancia 
- msg de whatsapp p/ voluntária
- msg de whatsapp p/ psr
- nome dos voluntários
- nome das psrs

**Comment by vivianedias** [comment]
As configurações serão salvas por módulo e em uma tabela separada - o nome provisório é `app-settings`, mas poderá sofrer modificações.

**Comment by vivianedias** [comment]
O input do formulario de configurações é um campo de texto, ou seja, se os usuarios quiserem colocar uma msg de whatsapp com espaçamento entre as linhas, eles não vão conseguir. O que funcionaria é um campo de textarea pro formulário, que ainda nao temos. Acho que faz sentido fazermos esse componente antes do release pq ele n parece custoso e o nao desenvolvimento dele vai atrasar o lançamento da pag de configs.

**Comment by lpirola** [comment]
@vivianedias faz todo  o sentido! agora entendi o q vc quis dizer com novo componente.

**Comment by vivianedias** [comment]
@igr-santos abro um pr no bonde-components?

**Comment by igr-santos** [comment]
@vivianedias pode abrir sim e geramos uma nova tag, a vantagem dessas bibliotecas é que não precisamos nos preocupar com release, a cada nova versão temos a possibilidade de atualizar ou não os clientes

**Comment by vivianedias** [comment]
Testes:

- [ ] Posso entrar em uma comunidade e setar distancia e mensagens de whatsapp atraves do formulario da página de configurações
- [ ] Essas infos são salvas no formulario (se vc recarregar a pag, as novas configs estão ali)
- [ ] Ao enviar uma msg de whatsapp p/ voluntaria, a mensagem setada no formulario esta configurada
- [ ] O mesmo vale pra PSR

**Comment by talitanovacoski** [comment]
### Testes
- Quando escrevo uma nova distância e dou enter, ele exibe o valor anterior outra vez antes de atualizar o campo. O mesmo aconteceu quando alterei a mensagem e cliquei em salvar, **parece que não salvou as alterações**, aí alguns segundos depois aparece a mensagem nova. Enviei vídeo no slack.
- Atualizar o **label do botão** para "salvar alterações" e colocá-lo à direita no topo, seguindo o style guide. "Enviar" pode dar a impressão de que vai enviar as msgs de whatsapp que foram alteradas.
- Exibir a notificação no canto da página quando as **configurações forem atualizadas** (balãozinho verde, como está no style guide), como feedback para o usuário de que foi salvo com sucesso.

#### Fluxo de encaminhamento
- Quando aparece o modal de "confirmar encaminhamento" o link **"voltar para o match"** está direcionando para a lista de voluntárias, corrigir para só fechar o modal e voltar para os resultados do match.
- Quando faço o encaminhamento e fecho o modal, sou direcionada para a lista de voluntárias sem **nenhum filtro aplicado**. Não deveria voltar para a tabela com os filtros que eu tinha selecionado antes de fazer o match?

#### Ajustes de layout:
- A **navegação** no topo não está seguindo o padrão dos outros módulos, foi usado o mesmo componente? O espaçamento ta beeem maior, fiz um video navegando entre dois módulos e mandei no slack.
- Ajustar o **label da aba "configurações"** para seguir o padrão (alinhado à esquerda, próximo das outras abas);
- Ajustar a **tela de configurações** pra seguir o padrão também (seguir o grid, título alinhado à esquerda, botão à direita). Vou prototipar isso aqui pra te ajudar.
- Na tela dos **resultados do match**, a largura da tabela ta menor do que o grid padrão, fazendo com que o botão apareça até a metade. Ajustar a tabela pra seguir o padrão do componente, ocupando todo o grid.

O restante funcionou bem! Mas acho importante esses pontos acima serem corrigidos antes de publicar.

![image.png](https://images.zenhubusercontent.com/5e148a9194d5c7299580d128/9f196e2e-1963-48f9-9a9e-5da7ff164329)

![Captura de Tela 2020-04-17 às 13.37.05.png](https://images.zenhubusercontent.com/5e148a9194d5c7299580d128/67c62e6e-25d3-4c52-9ba8-482d2347f16b)
