### ISSUE TITLE
Ajustes pós primeira semana de operação

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-microservices#215]
1. Atualizar paginação pra ir até 1000 pessoas;
2. Corrigir o modo de atualização dos dados na tabela. Os profissionais da saúde que já tiveram match feitos, continuam aparecendo na lista de disponíveis e isso pode gerar match duplicado;
3. Funcionalidade de busca nas listas de indivíduos e relacões;
Outros pontos levantados na reunião:
1. Poder mudar a ordenação da tabela de indivíduos para exibir os mais antigos primeiro;
2. Depois do match, voltar pra tabela de psicólogas no status que estava (paginação e filtros aplicados);
3. Como evitar que pessoas que estão com o whatsapp inválido sejam consideradas no match?;

**Comment by vivianedias** [comment]
@lpirola eu criei a issue #214 pra resolver o problema que a Talita levantou. Todos os outros (menores) já foram resolvidos, apenas a caixa de busca que não.
