### ISSUE TITLE
Publicação do zendesk-count

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-microservices#47]

**Comment by lpirola** [comment]
Ainda falta ativar webhook no zendesk.

**Comment by rolivegab** [comment]
Zendesk funcionando e testado com sucesso em todos os testes que fiz.
Ele atualiza tanto o ticket quanto o usuário no bonde, a partir do gatilho de disparo do zendesk.
Entretanto, não sei se o Elastic Apm está funcionando. Acho que só falta isso para fechar a issue.
