### ISSUE TITLE
Adicionar Elastic Apm em todos serviços

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-microservices#54]

**Comment by rolivegab** [comment]
Planejo começar o Elastic Apm no webhooks-registry, por ele ser um repositório pequeno, portanto, provavelmente será rápido para implementar.

Após isso, vou seguir com o webhooks-zendesk.

**Comment by lpirola** [comment]
O Gabriel colocou o apm apenas no cli-zendesk, webhooks-zendesk, webhooks-registry e webhooks-count.

https://github.com/nossas/bonde-microservices/pull/77
