### ISSUE TITLE
O cep incorreto está marcando usuárias quando o cep inicia-se por 0

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-microservices#73]
O problema pode ser no Mautic mas queria revisar essa situação e se for o caso pensar numa solução.

**Comment by lpirola** [comment]
Foco no problema da integração do mautic com o zendesk.

**Comment by rolivegab** [comment]
Para resolver o problema do cep, basta trocar o tipo do campo do CEP para string, ao invés de número.

**Comment by lpirola** [comment]
O problema não está no valor preenchido e sim na forma como os dados são esperados para que a integração funcione corretamente.

Será corrigido em https://github.com/nossas/bonde-microservices/issues/180
