### ISSUE TITLE
Na interface de match, o filtro das voluntárias no resultado não está filtrando como deveria com base na condição dela

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-microservices#84]

**Comment by lpirola** [comment]
Está sendo verificado a razão pela qual os dados não estão sendo atualizados com o cli-zendesk

**Comment by lpirola** [comment]
- [ ] Adicionar a coluna correta com a condição da mulher
- [ ] Corrigir bug com sincronização do cli-zendesk

**Comment by rolivegab** [comment]
Não consegui achar problemas com o código da sincronização do cli-zendesk.
Rodei todo tipo de teste.
Estou no momento verificando o banco de dados de produção para resolver o problema de inserção na tabela de matches.
